### ISSUE TITLE
Table view: sort by column

### ISSUE THREAD

**Issue by tothmate** [mitzu-io/mitzu#129]
Unsorted data (e.g. website views by screen size) is uncomprehensible without sorting:

<img width="843" alt="Screenshot 2023-02-16 at 11 44 00" src="https://user-images.githubusercontent.com/509063/219343668-e0853e3a-8e12-4613-82ad-cd6b63b23ffc.png">

**Comment by IstvanM** [comment]
Added sort + filter + paging + export button

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/4189234/222412594-994118a3-0756-4185-921c-08abe344a8ca.png">
